In [1]:
import numpy as np
from mastermind import mastermind
from q_agent import q_agent

env = mastermind()

In [2]:
env.reset()
env.render()

[['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']
 ['0' ' ' ' ' ' ' ' ' '0']]


In [3]:
env = mastermind()
env.reset()

print(env.goal_render)
print()

for i in np.random.randint(0, 8, 4):

    print(env.step(i))
    print()

env.render()
print()

['B' 'O' 'B' 'K']

(array([0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), -1, False, False)

(array([0, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), -1, False, False)

(array([0, 5, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), -1, False, False)

(array([1, 5, 2, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Training

In [4]:
agent = q_agent(env, env.state_dim, env.action_dim, epsilon=0.05, gamma=1, alpha=0.2, tol=1e-5)
q = agent.train(int(1e7))

  0%|                                                                                     | 0/10000000 [00:00<?, ?it/s]C:\Users\Dan\anaconda3\lib\site-packages\numpy\core\_methods.py:229: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
  0%|                                                                        | 14/10000000 [00:00<22:05:16, 125.76it/s]


Average td error: 1.0000, STD of STD: nan, Average ret: -48.00, Average steps: 12.00, Num_states: 48


  0%|                                                                      | 1020/10000000 [00:09<24:57:57, 111.25it/s]


Average td error: 0.9577, STD of STD: 4.05249402691488e-05, Average ret: -47.93, Average steps: 11.99, Num_states: 44585


  0%|                                                                      | 2027/10000000 [00:15<16:36:27, 167.22it/s]


Average td error: 0.9510, STD of STD: 2.1168582323758686e-05, Average ret: -47.95, Average steps: 11.99, Num_states: 88543


  0%|                                                                      | 2468/10000000 [00:18<20:28:16, 135.66it/s]



Average td error: 0.9490, STD of STD: 9.997109009096306e-06, Average ret: -48.00, Average steps: 12.00


In [5]:
env.goal_render

array(['B', 'O', 'B', 'K'], dtype='<U1')

# Test episode

In [6]:
state = env.reset()
step = 0

agent.epsilon = 0

while True:
    
    state, _, done, _ = env.step(agent.choose_action(tuple(state)))
    step += 1
    
    if done: break
        
env.render()

[['0' 'R' 'P' 'G' 'G' '1']
 ['1' 'R' 'K' 'W' 'K' '0']
 ['1' 'O' 'B' 'W' 'R' '1']
 ['0' 'K' 'K' 'P' 'R' '0']
 ['1' 'B' 'W' 'B' 'O' '1']
 ['1' 'Y' 'W' 'G' 'R' '1']
 ['0' 'W' 'W' 'Y' 'W' '1']
 ['0' 'B' 'Y' 'K' 'P' '0']
 ['0' 'B' 'B' 'O' 'R' '1']
 ['2' 'K' 'O' 'B' 'O' '0']
 ['0' 'K' 'P' 'K' 'P' '0']
 ['0' 'P' 'B' 'B' 'Y' '0']]
